        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 07 10:46:44 2015
        MODULE DX3ORDERC__genmod
          INTERFACE 
            SUBROUTINE DX3ORDERC(Y1,DX,U_B)
              REAL(KIND=8), INTENT(IN) :: Y1(3)
              REAL(KIND=8), INTENT(IN) :: DX
              REAL(KIND=8), INTENT(OUT) :: U_B
            END SUBROUTINE DX3ORDERC
          END INTERFACE 
        END MODULE DX3ORDERC__genmod
