        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 02 09:30:14 2015
        MODULE INITIAL_REF__genmod
          INTERFACE 
            SUBROUTINE INITIAL_REF
            END SUBROUTINE INITIAL_REF
          END INTERFACE 
        END MODULE INITIAL_REF__genmod
