        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 07 10:46:46 2015
        MODULE INITIAL_OUTFLOW__genmod
          INTERFACE 
            SUBROUTINE INITIAL_OUTFLOW
            END SUBROUTINE INITIAL_OUTFLOW
          END INTERFACE 
        END MODULE INITIAL_OUTFLOW__genmod
