        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 02 15:57:46 2015
        MODULE INITIAL_INIT__genmod
          INTERFACE 
            SUBROUTINE INITIAL_INIT
            END SUBROUTINE INITIAL_INIT
          END INTERFACE 
        END MODULE INITIAL_INIT__genmod
