        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 07 10:46:43 2015
        MODULE OUTPUT_TECOUT__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_TECOUT
            END SUBROUTINE OUTPUT_TECOUT
          END INTERFACE 
        END MODULE OUTPUT_TECOUT__genmod
