        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 07 10:46:43 2015
        MODULE OUTPUT_DEMENSIONLESS__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_DEMENSIONLESS(I)
              INTEGER(KIND=8), INTENT(IN) :: I
            END SUBROUTINE OUTPUT_DEMENSIONLESS
          END INTERFACE 
        END MODULE OUTPUT_DEMENSIONLESS__genmod
